### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by DerkDiggler21** [RegressiveIsProgressive/BTC-ETH-BSC-WalletHack-WalletRecovery-BTCSoloMine#1]
Do you have a contact TG please? Thank you :)

**Comment by BlackHatHacker1111** [comment]
> Do you have a contact TG please? Thank you :)

Message me on discord BlackHatHacker111#2333

**Comment by RegressiveIsProgressive** [comment]
> Do you have a contact TG please? Thank you :)

Linking new TG! Reopening educational testing if time and resources arise!
