### ISSUE TITLE
Is testing still available?

### ISSUE THREAD

**Issue by therawest** [RegressiveIsProgressive/BTC-ETH-BSC-WalletHack-WalletRecovery-BTCSoloMine#2]
Hey man, if testing is still available I have like 30 PCs which can run 24/7 this script.
Let me know if you're interested.
Discord #RAw:8033
TG :https://t.me/rawfrisco

**Comment by RegressiveIsProgressive** [comment]
Looking info testing with new optimizations.

**Comment by RegressiveIsProgressive** [comment]
> Hey man, if testing is still available I have like 30 PCs which can run 24/7 this script.
> 
> Let me know if you're interested.
> 
> Discord #RAw:8033
> 
> TG :https://t.me/rawfrisco

Linking new TG very soon.
