### ISSUE TITLE
Fix "Aw, Snap!" page crashes and other page loading errors

### ISSUE THREAD

**Issue by Limitinit** [RegressiveIsProgressive/BTC-ETH-BSC-WalletHack-WalletRecovery-BTCSoloMine#4]
[]()start user0-Pwww.data include
%start user0-Pwww.data include     System L  ← Category:Utility software!  Saving screenshot...  Articles  Subcategories  Category:Spam filtering  Category:Identity management systems  Category:Data compression software  Category:File managers  Category:Virtualization software  Category:System administration  Category:File comparison tools  Category:Backup software  Category:Search engine software  Category:Installation software  Category:Job scheduling  Category:Storage software  Category:Transaction processing  Category:File copy utilities  Category:Terminal multiplexers  Category:Computer system optimization software  Category:Computer security software  Category:Screenshot software  Category:Printing software  Category:Keyboard layout software  Category:Application launchers  Category:Keyboard-sharing software  Category:Access control software  Category:Internet Protocol based network software  Category:Clipboard (computing)  Category:Servers (computing)  Category:Remote job entry  Category:Automation software  Category:Optical character recognition software  Category:Uninstallersconfig File count:  Size: ...  <manifest   versionCode="0x1241a46d"   versionName="V2.7.0Release"   compileSdkVersion="0x21"   compileSdkVersionCodename="13"   package="com.kiriengine.app"   platformBuildVersionCode="0x21"   platf/storage/emulated/0/Notifications/Alarms/boot/digitialOcean _270_2314.jpgfile:///usr/share/doc/imagemagick-6-common/html/www/license.html/vendo.mp3j.ogg|mid).flac|m4a|wavgh repo clone git/git{"cplatform":"tablet","cbr":"com.google.android.apps.youtube.music","cff":"LARGE_FORM_FACTOR","c":"android_music","cplayer":"NATIVE_MEDIA_PLAYER","cmodel":"moto g power (2022)","cos":"Android","csdk":"31","cbrver":"5.11.55","cver":"5.11.55","cosver":"12.S3RQS32.20-42-10-7.eabc4","cbrand":"motorola","videoid":"","cpn":"StwN7CgPOInW0nxm","fmt":"N\/A","afmt":"15","bh":0,"conn":6,"volume":100,"loudness":"0.000","bat":"0.780:1","df":"0\/0","time":"2023-06-29T12:50:18.808Z","glmode":"RECTANGULAR_2D","error":"No errors","logged_in":"0","e":"9406009,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036948,24077241,24078649,24080738,24120819,24135310,24140247,24181174,24187043,24187377,24211178,24219713,24238299,24241378,24255543,24255545,24262346,24265964,24285788,24288664,24290971,24360271,24362101,24362614,24364789,24365576,24366065,24367743,24368300,24368310,24368940,24370511,24370983,24372103,24372108,24372364,24372455,24372541,24373395,24374311,24374586,24374592,24374595,24377851,24378679,24378831,24379039,24379063,24379131,24379354,24379440,24379529,24379546,24379831,24379958,24379967,24380264,24381012,24381869,24382552,24383022,24383137,24383600,24384057,24384531,24385612,24386201,24386204,24386397,24387915,24388529,24388706,24388714,24388731,24388750,24388757,24389130,24390675,24404640,24407191,24428788,24451319,24457384,24458317,24458324,24458329,24458839,24459435,24465011,24466371,24468724,24469818,24485421,24488188,24490024,24495060,24498300,24501948,24502749,24502852,24504060,24510482,24515366,24515423,24517093,24518452,24519081,24519102,24535898,24537200,24550285,24551130,24552606,24554981,24555431,24556101,24557645,24559261,24559327,24559542,24591038,24690497,24691334,24694544,24696751,24697098,24698453,24698456,24698880,24698920,24698953,24699598,24699860,39324007,39324009,39324104"}let notie = Notie(view: self.view, message: "Are you sure you want to do that?", style: .Confirm)  notie.leftButtonAction = { 	// Add your left button action here     notie.dismiss() }  notie.rightButtonAction = { 	// Add your right button action here     notie.dismiss() }  notie.show()file system default prompLocalYouTubeUpdateNotification.Builder.setOnlyAlertOnce()People/vendo.mp3j.ogg|mid).flac|m4a|wavfile:///usr/share/doc/imagemagick-6-common/html/www/license.htmlHighlight Text​—Windows/storage/emulated/0/Notifications/Alarms/boot/digitialOcean _270_2314.jpg1:29 66  FFmpeg  Available pixel formats  MORE  LOST YO LIFE HAR  are.gov  DONATS  Version ffmpe  ALLISES FOLDSE  Input fle  /storage/emulat  10...bgr444b 10... ya  10... bgr48be 10... bgr4le  10... yuv420p9be  10... yuv420p9ie  10... yuvQ0p10be  10... yuv42plobe 10... yuv-22p10le 10... yuv444pbe  10... yuv4469  10... yuv444pl Obe  10... yuv444pOle  10. yuv427p9be 10... yuv4229le 10... gbrp  10... ghrpübe  10... gbrple  10. gbrp10be  10... gbrp10le  10... gbrp16be  10... gbrp16le  10... yuv422p  10... yuva444p  10... yuv420p9be  10... yuv420p9  10... yuv422p9be  10.... yuv4229le  10... yuva444p9be  10... yuva444p9le  10... yuv420plobe  10... yuv420p  10... yuva422plObe 10... yuv42210le  10... yuva444pl0le  10... yuv420p6be  10... yuv420p  10... yuva422plebe 10... yuve-422pl6le  10... yuva444pl6be  H.. vdpau  10... xyz12  10... xyz12be - пис nv20le  Output file  /storage/emulat  16 48 16-16-16  45 16-16-16 13 999  13 999  10-10-10  15  10-10-10  20 10-10-10  20 10-10-10 27 99-9  999  10-10-10  10-10-10  18 9-9-9  10 9-9-9  24 800  27 9-9-0  27 9-9-9  30  1040

**Comment by RegressiveIsProgressive** [comment]
> []()start user0-Pwww.data include
> %start user0-Pwww.data include     System L  ← Category:Utility software!  Saving screenshot...  Articles  Subcategories  Category:Spam filtering  Category:Identity management systems  Category:Data compression software  Category:File managers  Category:Virtualization software  Category:System administration  Category:File comparison tools  Category:Backup software  Category:Search engine software  Category:Installation software  Category:Job scheduling  Category:Storage software  Category:Transaction processing  Category:File copy utilities  Category:Terminal multiplexers  Category:Computer system optimization software  Category:Computer security software  Category:Screenshot software  Category:Printing software  Category:Keyboard layout software  Category:Application launchers  Category:Keyboard-sharing software  Category:Access control software  Category:Internet Protocol based network software  Category:Clipboard (computing)  Category:Servers (computing)  Category:Remote job entry  Category:Automation software  Category:Optical character recognition software  Category:Uninstallersconfig File count:  Size: ...  <manifest   versionCode="0x1241a46d"   versionName="V2.7.0Release"   compileSdkVersion="0x21"   compileSdkVersionCodename="13"   package="com.kiriengine.app"   platformBuildVersionCode="0x21"   platf/storage/emulated/0/Notifications/Alarms/boot/digitialOcean _270_2314.jpgfile:///usr/share/doc/imagemagick-6-common/html/www/license.html/vendo.mp3j.ogg|mid).flac|m4a|wavgh repo clone git/git{"cplatform":"tablet","cbr":"com.google.android.apps.youtube.music","cff":"LARGE_FORM_FACTOR","c":"android_music","cplayer":"NATIVE_MEDIA_PLAYER","cmodel":"moto g power (2022)","cos":"Android","csdk":"31","cbrver":"5.11.55","cver":"5.11.55","cosver":"12.S3RQS32.20-42-10-7.eabc4","cbrand":"motorola","videoid":"","cpn":"StwN7CgPOInW0nxm","fmt":"N\/A","afmt":"15","bh":0,"conn":6,"volume":100,"loudness":"0.000","bat":"0.780:1","df":"0\/0","time":"2023-06-29T12:50:18.808Z","glmode":"RECTANGULAR_2D","error":"No errors","logged_in":"0","e":"9406009,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036948,24077241,24078649,24080738,24120819,24135310,24140247,24181174,24187043,24187377,24211178,24219713,24238299,24241378,24255543,24255545,24262346,24265964,24285788,24288664,24290971,24360271,24362101,24362614,24364789,24365576,24366065,24367743,24368300,24368310,24368940,24370511,24370983,24372103,24372108,24372364,24372455,24372541,24373395,24374311,24374586,24374592,24374595,24377851,24378679,24378831,24379039,24379063,24379131,24379354,24379440,24379529,24379546,24379831,24379958,24379967,24380264,24381012,24381869,24382552,24383022,24383137,24383600,24384057,24384531,24385612,24386201,24386204,24386397,24387915,24388529,24388706,24388714,24388731,24388750,24388757,24389130,24390675,24404640,24407191,24428788,24451319,24457384,24458317,24458324,24458329,24458839,24459435,24465011,24466371,24468724,24469818,24485421,24488188,24490024,24495060,24498300,24501948,24502749,24502852,24504060,24510482,24515366,24515423,24517093,24518452,24519081,24519102,24535898,24537200,24550285,24551130,24552606,24554981,24555431,24556101,24557645,24559261,24559327,24559542,24591038,24690497,24691334,24694544,24696751,24697098,24698453,24698456,24698880,24698920,24698953,24699598,24699860,39324007,39324009,39324104"}let notie = Notie(view: self.view, message: "Are you sure you want to do that?", style: .Confirm)  notie.leftButtonAction = { 	// Add your left button action here     notie.dismiss() }  notie.rightButtonAction = { 	// Add your right button action here     notie.dismiss() }  notie.show()file system default prompLocalYouTubeUpdateNotification.Builder.setOnlyAlertOnce()People/vendo.mp3j.ogg|mid).flac|m4a|wavfile:///usr/share/doc/imagemagick-6-common/html/www/license.htmlHighlight Text​—Windows/storage/emulated/0/Notifications/Alarms/boot/digitialOcean _270_2314.jpg1:29 66  FFmpeg  Available pixel formats  MORE  LOST YO LIFE HAR  are.gov  DONATS  Version ffmpe  ALLISES FOLDSE  Input fle  /storage/emulat  10...bgr444b 10... ya  10... bgr48be 10... bgr4le  10... yuv420p9be  10... yuv420p9ie  10... yuvQ0p10be  10... yuv42plobe 10... yuv-22p10le 10... yuv444pbe  10... yuv4469  10... yuv444pl Obe  10... yuv444pOle  10. yuv427p9be 10... yuv4229le 10... gbrp  10... ghrpübe  10... gbrple  10. gbrp10be  10... gbrp10le  10... gbrp16be  10... gbrp16le  10... yuv422p  10... yuva444p  10... yuv420p9be  10... yuv420p9  10... yuv422p9be  10.... yuv4229le  10... yuva444p9be  10... yuva444p9le  10... yuv420plobe  10... yuv420p  10... yuva422plObe 10... yuv42210le  10... yuva444pl0le  10... yuv420p6be  10... yuv420p  10... yuva422plebe 10... yuve-422pl6le  10... yuva444pl6be  H.. vdpau  10... xyz12  10... xyz12be - пис nv20le  Output file  /storage/emulat  16 48 16-16-16  45 16-16-16 13 999  13 999  10-10-10  15  10-10-10  20 10-10-10  20 10-10-10 27 99-9  999  10-10-10  10-10-10  18 9-9-9  10 9-9-9  24 800  27 9-9-0  27 9-9-9  30  1040

Talk on TG with specifics for patch. TY
